name: Visa Monitor

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

concurrency:
  group: visa-monitor
  cancel-in-progress: true

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python monitor.py
        env:
          TG_TOKEN: ${{ 8637032817:AAF_6yxAy4PtAk5gx4tZTarUR3vU9aKMCO0 }}
          TG_CHAT_ID: ${{ 8286527092 }}
